# Generated by Django 6.0.5 on 2026-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0002_add_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queryfeedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="queryfeedback",
            name="ai_engine_qf_user_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="querylog",
            name="ai_engine_q_retr_conf_idx",
        ),
        migrations.RemoveIndex(
            model_name="querylog",
            name="ai_engine_q_created_idx",
        ),
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="ai_engine_d_documen_da7790_idx",
            old_name="ai_engine_d_documen_idx",
        ),
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="ai_engine_d_documen_560102_idx",
            old_name="ai_engine_d_documen_owner_idx",
        ),
        migrations.AlterField(
            model_name="queryfeedback",
            name="comment",
            field=models.TextField(blank=True, help_text="Optional feedback comment"),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="llm_model",
            field=models.CharField(default="mistral", max_length=100),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="retrieval_confidence",
            field=models.FloatField(
                default=0.0, help_text="Average relevance score of retrieved chunks"
            ),
        ),
    ]
